## Q1. What are the benefits of the built-in array package, if any?

    Arrays represent multiple data items of the same type using a single name. In arrays, the elements can be accessed         randomly by using the index number. Arrays allocate memory in contiguous memory locations for all its elements. Hence       there is no chance of extra memory being allocated in case of arrays. This avoids memory overflow or shortage of memory     in arrays.

## Q2. What are some of the array package's limitations ?

    1. Only consists of elements belonging to the same data type
    2. Need to explicitly import a module for declaration
    3. Insertion and deletion are quite difficult in an array as the elements are stored in consecutive memory locations          and the shifting operation is costly.
    4. A loop has to be formed to print or access the components of array
    5. The number of elements to be stored in an array should be known in advance.
    6. An array is a static structure (which means the array is of fixed size). Once declared the size of the array cannot        be modified. The memory which is allocated to it cannot be increased or decreased.


## Q3. Describe the main differences between the array and numpy packages ?

    The array package doesn't provide any help with numerical calculation with the items insdie it in number form while         NumPy give you a wide variety of numerical operations.
    
    The array package doesn't provide any help with numerical calculation with the items insdie it in number form while         NumPy give you a wide variety of numerical operations.

    An array is a single dimensional entity which hold the numerical data, while numpy can have more than 1 dimension.

    In case of array, item can be accessed by its index position and it is easy task while in numpy item is accessed by its     column and row index, which makes it slightly time taking. Same goes with appending operation.

## Q4. Explain the distinctions between the empty, ones, and zeros functions ?

In [5]:
import numpy as np
l = [2,2,4]  ## it will convert all element inside a table to zero
np.zeros(l)  

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [7]:
np.ones(l) ## it will convert all element inside a table to one

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [10]:
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


## Q5. In the fromfunction function, which is used to construct new arrays, what is the role of the callable argument ?

    Syntax : numpy.fromfunction(function, shape,  dtype)
    function : [callable] The function is called with N parameters, where N is the rank of shape. Each parameter represents     the coordinates of the array varying along a specific axis.

    shape : [(N, ) tuple of ints] Shape of the output array, which also determines the shape of the coordinate arrays           passed to function.

    dtype : [data-type, optional] Data-type of the coordinate arrays passed to function.

In [11]:
import numpy as np
a1 = np.fromfunction(lambda i,j:i+j,(4,4),dtype = float)
print(a1)

[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]


## Q6. What happens when a numpy array is combined with a single-value operand (a scalar, such as an int or a floating-point value) through addition, as in the expression A + n ?

    If any scaler value such as integer is added to the numpy array then all the elements inside the array will add that       value in it.

## Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome ?

In [13]:
import numpy as np
a1 = np.fromfunction(lambda i,j:i+j,(4,4),dtype = float)

print(a1)

a1 += 3
print(a1)

a1 *= 3
print(a1)
""" It will carry out provided operation on all elements of array."""


[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]
[[3. 4. 5. 6.]
 [4. 5. 6. 7.]
 [5. 6. 7. 8.]
 [6. 7. 8. 9.]]
[[ 9. 12. 15. 18.]
 [12. 15. 18. 21.]
 [15. 18. 21. 24.]
 [18. 21. 24. 27.]]


' It will carry out provided operation on all elements of array.'

## Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays ?

    Yes, it is possible that we can include a string of fixed length in numpy array. The dtype of any numpy array               containing string values is the maximum length of any string present in the array.Once set, it will only be able to         store new string having length not more than the maximum length at the time of the creation. If we try to reassign some     another string value having length greater than the maximum length of the existing elements, it simply discards all the     values beyond the maximum length accept upto those values which are under the limit.

## Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays ?

    It will simply add or multiply element to element at same position.

## Q10. What is the best way to use a Boolean array to mask another array ?

    The best way to use a Boolean array to mask another array is by Using masked_where of numpy package

## Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute ?

    np.std and math package can be used individually.

## 12. What is the dimensionality of a Boolean mask-generated array ?

    It will have same dimensionality as input array.